name: chat_flutter_example
description: "Demo app for the chat_flutter package."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  chat_flutter:
    path: ../
  go_router: ^15.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
